apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc1
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      containers:
      - name: c30
        image: siva2626/flask10:v1
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: f1-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - targetPort: 5000
      port: 84
