apiVersion: apps/v1
kind: Deployment
metadata:
  name:  spc1
  namespace: siva-k8s
  labels:
    app: spk-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      containers:
      - name: c26
        image: siva2626/spk:v1
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - targetPort: 8080
      port: 82
