apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flask-deploy
  labels: 
    app: python-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: frontend
  template: 
    metadata:
      name: pod2
      labels:
        app: frontend
    spec:
      containers:
      - name: c27
        image: us-east1-docker.pkg.dev/siva-477505/repo1/flask10:v1
        ports:
        - containerPort: 5000
