apiVersion: apps/v1
kind: Deployment
metadata:
  name: spk
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      containers:
      - name: c30
        image: siva2626/spk:v2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spk-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - targetPort: 8080
      port: 84
